language: node_js
node_js: "8"
sudo: required
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - yarn install
install:
  - npm install -g codecov
script:
  - yarn test-ci
  - yarn build
after_success:
  - if [[ $TRAVIS_PULL_REQUEST == 'false' ]] && [[ $TRAVIS_BRANCH == 'master' ]]; then
      chmod ugo+x ./scripts/update_demo.sh;
      chmod ugo+x ./scripts/demo-deploy-comment.sh;
      bash ./scripts/update_demo.sh;
      bash ./scripts/demo-deploy-comment.sh;
    fi
cache:
  yarn: true
  directories:
    - ~/.npm
git:
  depth: 1
deploy:
  - provider: script
    on:
      branch: master
    script:
    - npx semantic-release
    skip_cleanup: true
